#include "cmd_options.h"
#include <glib.h>

AppFlags app_flags = { NULL, NULL, NULL, FALSE, NULL };
DebugFlags debug_flags = { FALSE, FALSE, FALSE };

const GOptionEntry cmd_options[] = { // freed before exit
    { "version",
      'v',
      0,
      G_OPTION_ARG_NONE,
      &debug_flags.version,
      "Show version information",
      NULL },
    { "paperparser",
      'p',
      0,
      G_OPTION_ARG_FILENAME,
      &app_flags.paperparser_path,
      "Specify the path to the paperparser binary",
      NULL },
    { "cache",
      'c',
      0,
      G_OPTION_ARG_FILENAME,
      &app_flags.cache_path,
      "Specify the path to the cache file",
      NULL },
    { "json",
      'j',
      0,
      G_OPTION_ARG_FILENAME,
      &app_flags.json_path,
      "Specify the path to the JSON file",
      NULL },
    { "debug",
      'd',
      0,
      G_OPTION_ARG_NONE,
      &debug_flags.debug,
      "Enable debug output",
      NULL },
    { "import",
      'i',
      0,
      G_OPTION_ARG_FILENAME_ARRAY,
      &app_flags.import_paths,
      "Import file(s) or directory(ies)",
      "File..." },
    { "list",
      'l',
      0,
      G_OPTION_ARG_NONE,
      &app_flags.list,
      "List all papers in the database",
      NULL },
    { "mock-data",
      'm',
      0,
      G_OPTION_ARG_NONE,
      &debug_flags.mock_data,
      "Use mock data for testing",
      NULL },
    { 0 }
};
